export const myprojects = [
   {
    projecttitle: "Event Ease App",
    category: ["flutter"],
    desc: "Event Ease is an innovative platform designed for event management.",
    imgpath: "./eventease.png",
    link: "https://drive.google.com/drive/folders/1of0cqTmzWHOTJPBNc9FCA8nEiaQHqKix?usp=sharing",
    github:"https://github.com/ahmedbhyy/eventease",
  },
  {
    projecttitle: "Complete Nutrition",
    category: ["flutter"],
    desc: "I developed a complete software solution for nutrition businesses, featuring sales management, inventory tracking.",
    imgpath: "./completevente.png",
    link: "https://github.com/ahmedbhyy/americanwolfvente",
    github:"https://github.com/ahmedbhyy/americanwolfvente",
  }, 
  {
    projecttitle: "Errayen App",
    category: ["flutter"],
    desc: "Errayen App is a comprehensive platform designed to streamline the management of real estate agencies.",
    imgpath: "./errayen.png",
    link: "https://github.com/ahmedbhyy/errayenprogram",
    github:"https://github.com/ahmedbhyy/errayenprogram",
  }, 
  {
    projecttitle: "Fortes femenao App",
    category: ["flutter"],
    desc: "Fortes Feminae is a collaborative e-learning platform designed to empower women through accessible and engaging learning experiences.",
    imgpath: "./fortes2.png",
    link: "https://drive.google.com/file/d/1ZIVePZGmuVaS75r2qLhJZon229pTzkbj/view",
    github:"https://github.com/ahmedbhyy/fortess_femenao",
  }, 
   {
    projecttitle: "AmericanWolf",
    category: ["flutter"],
    desc: "I developed a stock management and manufacturing order program for a protein production industry.",
    imgpath: "./americanwolf.png",
    link: "https://github.com/ahmedbhyy/americanwolf",
    github:"https://github.com/ahmedbhyy/americanwolf",
  }, 
    {
    projecttitle: "Fortes femenao Website",
    category: ["react"],
    desc: "Fortes Feminae is a collaborative e-learning platform designed to empower women through accessible and engaging learning experiences.",
    imgpath: "./fortes1.png",
    link: "https://drive.google.com/file/d/1Dxh6ed0m_jRvS8HxdpL1OKci_J38zhRN/view",
    github:"https://github.com/ahmedbhyy/fortess_femenao",
  },
   {
    projecttitle: "Cocos Website",
    category: ["react"],
    desc: "I developed a website for Cocos Café, designed to showcase their menu in an appealing and user-friendly way, allowing customers to easily explore their offerings online.",
    imgpath: "./cocos.png",
    link: "https://cocos.tn/",
    github:"https://github.com/sanaanidhal/Cocos-react",
  },
  {
    projecttitle: "ICF Tunisie",
    category: ["css"],
    desc: "I developed the official website for ICF Tunisie, a company specializing in the design and manufacture of tools and cutting forms for the soft materials printing industry.",
    imgpath: "./icf.png",
     link: "https://icftunisie.com/",
    github:"https://github.com/ahmedbhyy/icfproject-main",
  },
  {
    projecttitle: "Errayen",
    category: ["css"],
    desc: "Developed the official website for Errayen, a real estate company, highlighting their properties and services with a user-friendly design.",
    imgpath: "./errayensite.png",
     link: "https://errayen.com/",
    github:"https://github.com/sanaanidhal/Errayen-vite",
  },{
    projecttitle: "Maison Jerbi",
    category: ["css"],
    desc: "I created the official website for Maison Jerbi, a charming guest house located in Henchir Goret, Nabeul.",
    imgpath: "./maisonjerbi.png",
     link: "https://maisonjerbi.com/",
    github:"https://github.com/ahmedbhyy/maisonjerbi",
  },
  {
    projecttitle: "Sup'Clubs App",
    category: ["flutter"],
    desc: "Sup'clubs embodies my dedication to enriching student life and fostering collaboration within educational institutions. Designed specifically for clubs within SUP'COM.",
    imgpath: "./supclubs.png",
    link: "https://play.google.com/store/apps/details?id=com.supclubs.supcom",
    github:"https://github.com/ahmedbhyy/supclubs2",
  },
  {
    projecttitle: "Baraka App",
    category: ["flutter"],
    desc: "Developed for a company, this mobile application revolutionizes financial management within the domain of agriculture, offering streamlined solutions to enhance operational efficiency and fiscal accountability.",
    imgpath: "./baraka.png",
     link: "https://github.com/ahmedbhyy/bhyapp",
    github:"https://github.com/ahmedbhyy/bhyapp",
  },
  {
    projecttitle: "GardienLock",
    category: ["flutter"],
    desc: "GuardianLock: Face Recognition Car Security 🚗👤 Enhance your car's security with GuardianLock, a Flutter app using advanced face recognition. Only authorized users can access the vehicle, offering an accessible user interface. 🛡️🔐",
    imgpath: "./gothom.png",
     link: "https://github.com/ahmedbhyy/gothomhack",
    github:"https://github.com/ahmedbhyy/gothomhack",
  },
  {
    projecttitle: "Sup'Bike",
    category: ["flutter"],
    desc: "SupBike is the all-in-one app designed to revolutionize the biking experience on our university campus. With SupBike, students, faculty, and staff can easily locate and manage their bikes, ensuring a hassle-free and secure ride every time.",
    imgpath: "./supbike.png",
     link: "https://supcom-my.sharepoint.com/personal/ahmed_belhajyahia_supcom_tn/_layouts/15/stream.aspx?id=%2Fpersonal%2Fahmed%5Fbelhajyahia%5Fsupcom%5Ftn%2FDocuments%2FPi%C3%A8ces%20jointes%2Fsupbike%2Ewebm&ct=1715991728399&or=OWA%2DNT%2DMail&cid=e0164773%2D5e03%2D1776%2Dbd91%2D9fcea9e0a620&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E18d13c2f%2D67eb%2D41e6%2D8bd2%2D904f8269aa44",
    github:"https://github.com/ahmedbhyy/supbike",
  },
  {
    projecttitle: "Cominos App",
    category: ["flutter"],
    desc: "Cominos Learn is the ultimate app for parents who want to stay connected with their children’s education and ensure their safety. Combining powerful learning tools with advanced tracking features.",
    imgpath: "./cominos.png",
     link: "https://supcom-my.sharepoint.com/personal/ahmed_belhajyahia_supcom_tn/_layouts/15/stream.aspx?id=%2Fpersonal%2Fahmed%5Fbelhajyahia%5Fsupcom%5Ftn%2FDocuments%2FPi%C3%A8ces%20jointes%2Fvideo2%2Ewebm&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E334e8906%2D3297%2D4218%2Dab2f%2Ddf54b1216858&ct=1715991892905&or=OWA%2DNT%2DMail&cid=59039388%2Dc2f4%2D78f9%2Dae2b%2De71cde0f439f&ga=1",
    github:"https://github.com/ahmedbhyy/mutualhack",
  },
  {
    projecttitle: "Banky App",
    category: ["flutter"],
    desc: "Banky is the ultimate banking app designed to make managing your finances easy, secure, and convenient. Whether you're handling everyday transactions, saving for the future, or tracking your spending, Banky has you covered",
    imgpath: "./bank.png",
     link: "https://drive.google.com/file/d/1ZlgV35_nlPbuYP7IHbfYVyC0dwqwFyRb/view",
    github:"https://github.com/ahmedbhyy/bankpfe",
  },
  {
    projecttitle: "React Portfolio",
    category: ["react"],
    desc: "Welcome to my portfolio, a dynamic and interactive showcase of my skills and projects as a web developer. Built using React and styled with CSS, this portfolio highlights my proficiency in modern web development technologies.",
    imgpath: "./portfolio.png",
     link: "https://myportfolio-73fb8.web.app/",
    github:"https://github.com/ahmedbhyy/portfolio1",
  },

  {
    projecttitle: "Portfolio",
    category: ["css"],
    desc: "Welcome to my first portfolio, a showcase of my journey and skills as a budding web developer. Built from scratch using HTML and CSS, this portfolio reflects my dedication to learning and my passion for creating beautiful, functional web designs.",
    imgpath: "./portfolio1.png",
     link: "https://ahmedbhy.vercel.app/",
    github:"https://github.com/ahmedbhyy/portfolio",
  },
  
];