export const myprojects = [
  
  {
    projecttitle: "Sup'Clubs App",
    category: ["flutter"],
    desc: "Sup'clubs embodies my dedication to enriching student life and fostering collaboration within educational institutions. Designed specifically for clubs within SUP'COM.",
    imgpath: "./supclubs.png",
    link: "",
    github:"https://github.com/ahmedbhyy/supclubs2",
  },
  {
    projecttitle: "Baraka App",
    category: ["flutter"],
    desc: "Developed for a company, this mobile application revolutionizes financial management within the domain of agriculture, offering streamlined solutions to enhance operational efficiency and fiscal accountability.",
    imgpath: "./baraka.png",
     link: "",
    github:"https://github.com/ahmedbhyy/bhyapp",
  },
  {
    projecttitle: "GardienLock",
    category: ["flutter"],
    desc: "GuardianLock: Face Recognition Car Security 🚗👤 Enhance your car's security with GuardianLock, a Flutter app using advanced face recognition. Only authorized users can access the vehicle, offering an accessible user interface. 🛡️🔐",
    imgpath: "./gothom.png",
     link: "",
    github:"https://github.com/ahmedbhyy/gothomhack",
  },
  {
    projecttitle: "Sup'Bike",
    category: ["flutter"],
    desc: "SupBike is the all-in-one app designed to revolutionize the biking experience on our university campus. With SupBike, students, faculty, and staff can easily locate and manage their bikes, ensuring a hassle-free and secure ride every time.",
    imgpath: "./supbike.png",
     link: "",
    github:"https://github.com/ahmedbhyy/supbike",
  },
  {
    projecttitle: "Cominos App",
    category: ["flutter"],
    desc: "Cominos Learn is the ultimate app for parents who want to stay connected with their children’s education and ensure their safety. Combining powerful learning tools with advanced tracking features.",
    imgpath: "./cominos.png",
     link: "",
    github:"https://github.com/ahmedbhyy/mutualhack",
  },
  {
    projecttitle: "Banky App",
    category: ["flutter"],
    desc: "Banky is the ultimate banking app designed to make managing your finances easy, secure, and convenient. Whether you're handling everyday transactions, saving for the future, or tracking your spending, Banky has you covered",
    imgpath: "./bank.png",
     link: "",
    github:"https://github.com/ahmedbhyy/bankpfe",
  },
  {
    projecttitle: "React Portfolio",
    category: ["react"],
    desc: "Welcome to my portfolio, a dynamic and interactive showcase of my skills and projects as a web developer. Built using React and styled with CSS, this portfolio highlights my proficiency in modern web development technologies.",
    imgpath: "./portfolio.png",
     link: "",
    github:"",
  },
  {
    projecttitle: "Portfolio",
    category: ["css"],
    desc: "Welcome to my first portfolio, a showcase of my journey and skills as a budding web developer. Built from scratch using HTML and CSS, this portfolio reflects my dedication to learning and my passion for creating beautiful, functional web designs.",
    imgpath: "./portfolio1.png",
     link: "https://ahmedbhy.vercel.app/",
    github:"https://github.com/ahmedbhyy/portfolio",
  },
];